version: '3'

networks:
  laravel:

services:
  php:
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: php
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./vhosts.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: portal
      MYSQL_USER: greekparliament
      MYSQL_PASSWORD: Vouli1!
      MYSQL_ROOT_PASSWORD: kostass
    networks:
      - laravel

